---
- hosts: web
  become: yes
  roles:
    - caddy
    - caddy_mods
  vars_files:
    - group_vars/stages/{{ stage }}.yml 
  tasks:
    - name: Install packages
      apt:
        pkg: "{{ item }}"
        state: installed
      with_items:
        - hugo
