---
- hosts: web
  become: yes
  roles:
    - common
    # https://github.com/jnv/ansible-role-unattended-upgrades
    - unattended-upgrades
    - binaries
  vars_files:
    - group_vars/stages/{{ stage }}.yml 
