---
- hosts: web
  become: yes
  roles:
    # - common
    # https://github.com/jnv/ansible-role-unattended-upgrades
    # - unattended-upgrades
    - binaries
    - caddy_ansible
    - caddy_addons
    - docker-ce
    - docker-apps
    - users
  vars_files:
    - group_vars/stages/{{ stage }}.yml 




# @TODO 
# https://caddyserver.com/download/darwin/amd64?plugins=http.git,http.ipfilter&license=personal&telemetry=off

