---
# defaults file for caddy-ansible
caddy_user: www-data
caddy_home: /home/caddy
caddy_features: git
caddy_update: yes
caddy_config: |
  localhost:2020
  gzip
  root /var/www
  git github.com/antoiner77/caddy-ansible /
