---
# Docker-py issues: 
#  https://github.com/ansible/ansible-modules-core/issues/4246
#  https://github.com/ansible/ansible/issues/17495
#  https://github.com/ansible/ansible-modules-core/issues/3763
- name: Install pip
  apt:
    pkg: python-pip
    state: installed

- name: Install docker-py
  pip: 
    name: docker-py 
    version: 1.9.0
    # executable: /usr/local/bin/pip

- name: Checkout project from github
  git:
    repo: https://github.com/TBeijen/tbnl-2003
    dest: "{{ caddy_home }}/docker_apps/tbnl_2003"
  become: yes
  become_user: "{{ caddy_user }}"

- name: Build docker image
  docker_image:
    name: tbnl_2003
    path: "{{ caddy_home }}/docker_apps/tbnl_2003"
    state: present