---
# Based on: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04

# apt-get update
- name: Update apt cache
  apt:
    update_cache: yes

# apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
- name: Add docker repository GPG key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

# apt-add-repository 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
- name: Add docker repository
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main

# apt-get update
- name: Update apt cache (#2)
  apt:
    update_cache: yes

# apt-get install -y docker-engine
- name: Install docker-engine
  apt:
    name: docker-engine

- name: Ensure docker running and enable
  service:
    name: docker
    state: started
    enabled: yes

- name: Register current users
  shell: awk -F':' '{ print $1}' /etc/passwd
  changed_when: false
  register: current_users

- name: Add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  when: item in current_users.stdout_lines
  with_items: "{{ docker_users }}"